import { useEffect, useState } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Card from '../components/Card'
import { Typewriter } from 'react-simple-typewriter';

// import json from '../data.json';

const json = {
     "data": {

          "cocktails": {
               "0": {
                    "name": "Tokyo ice tee",
                    "picture": "Tokyo_ice_tee",

                    "ingredients": [
                         "Developing a Website Builder.",
                         "Using REACT with NEXTJS, for styling MATERIAL UI (MUI), STRAPI for contains management system (CMS), for animation FRAMER MOTION and directly SVG’s manipulation."
                    ]
               },
               "1": {
                    "name": "Hung cay",
                    "picture": "Hung_cay",

                    "ingredients": [
                         "Developing a Website Builder.",
                         "Using REACT with NEXTJS, for styling MATERIAL UI (MUI), STRAPI for contains management system (CMS), for animation FRAMER MOTION and directly SVG’s manipulation."
                    ]
               }


          }

     }
}

export default function Home() {



     const title = (
          <h1 className={styles.title}>
               Cocktails
          </h1>
     )
     const description = (
          <p className={styles.description}>
               <Typewriter
                    words={['How to make cocktails']}
                    cursor
                    cursorStyle='_'
                    typeSpeed={80}
               />
          </p>
     )

     const main = (
          <div className={styles.grid}>
               {/* {console.log(json.data.cocktails[0].name)} */}
               <Card name={'Tokyo Ice Tee'} picture={'Tokyo_ice_tee'} />
               <Card name={'Saigon Lanton'} picture={'Saigon_Lanton'} />
               <Card name={'Cham Island'} picture={'Cham_Island'} />

               <Card name={'Hung Cay'} picture={'Hung_cay'} />
               <Card name={'His Pearl Martini'} picture={'His_Pearl_Martini '} />
               <Card name={'Espresso Martini'} picture={'Espresso_Martini'} />
               <Card name={'Trainor Tan'} picture={'Trainor_Tan'} />

               <Card name={'Watermelon Martini'} picture={'Watermelon_Martini'} />
               <Card name={'Negroni'} picture={'Negroni'} />
               <Card name={'Nha Trang Breeze'} picture={'Nha_Trang_Breeze'} />
               <Card name={'Ap Erik Spirits'} picture={'Ap_erik_spirits'} />
               <Card name={'Pornostar Martini'} picture={'Pornostar_martini'} />

          </div>
     )

     const footer = (
          <footer className={styles.footer}>
               <a
                    href="https://www.houseofho.co.uk"
                    target="_blank"
                    rel="noopener noreferrer"
               >
                    Powered by{' '}
                    <div style={{ color: '#db0000' }} >
                         THE HOUSE OF HÔ
                    </div>
                    <div className={styles.logo}>
                         {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}

                    </div>
               </a>
          </footer>
     )

     return (
          <div className={styles.container}>
               <Head>
                    <title>🍸 How to make cocktails 🍹</title>
                    <meta name="description" content="Generated by create next app" />
               </Head>
               <main className={styles.main}>
                    {title}
                    {description}
                    {main}
               </main>
               {footer}
          </div>
     )
}
